AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lead Scouting Agent (FastAPI) on AWS Lambda + API Gateway

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  LeadScoutingApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: app.aws_lambda.handler
      Runtime: python3.11
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          APP_ENV: prod
          FOCUS_CONFIG_PATH: config/focus.yaml
